version: "3.9"
services:
  world:
    build: .
    ports:
      - "7777"
    environment:
      THREAD_GAME_MIN: 1
      THREAD_GAME_MAX: 2
      THREAD_SERVICE_MIN: 1
      THREAD_SERVICE_MAX: 4
      CLUSTER_ADDRESS: 127.0.0.1
      CLUSTER_INTERFACE: 127.0.0.1
      DB_URL: "jdbc:postgresql://postgres-world:5432/finex_world?currentSchema=public"
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: postgres
      AUTH_HOST: l2j-auth
      AUTH_PORT: 9014
      SERVER_HOST: "*"
      SERVER_PORT: 7777
      SERVER_BACKLOG: 100
  postgres-world:
    image: "postgres:12"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finex_world