version: "3.9"
services:
  worldserver:
    build: .
    ports:
      - "7777"
    environment:
      THREAD_GAME_MIN: 1
      THREAD_GAME_MAX: 2
      THREAD_SERVICE_MIN: 1
      THREAD_SERVICE_MAX: 4
      REDIS_ADDRESS: "redis://finex-redis:6379"
      DB_URL: "jdbc:postgresql://postgres-world:5432/finex_world?currentSchema=public"
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVER_HOST: "*"
      SERVER_PORT: 7777
      SERVER_BACKLOG: 100
  postgres-world:
    image: "postgres:12"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finex_world
  finex-redis:
    image: "redis:6.2.5-alpine"